---
title: "R for NB"
author: "Sangeetha"
date: "2022-10-13"
output: html_document
---

```{r}
library(naivebayes)
library(dplyr)
library(ggplot2)
library(psych)
library(e1071)
```



```{r}
data <- read.csv("../../data/GlobalLandTemperaturesByMajorCity.csv")
data$dt <- as.Date(data$dt)

NB_data = select(data, -Latitude, -Longitude, -dt, -City)
NB_data = NB_data %>% mutate(Label =
                     case_when(NB_data$AverageTemperature > 22 & NB_data$AverageTemperature < 25  ~ "Normal", 
                               NB_data$AverageTemperature >= 25 ~ "High",
                               NB_data$AverageTemperature < 22  ~ "Low")
)
head(NB_data)
str(data)
```
```{r}

# Plot
ggplot(NB_data, aes(x=Country, y=AverageTemperature)) + 
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Ordered Bar Chart", 
       subtitle="Make Vs Avg. Mileage", 
       caption="source: mpg") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6))
```


```{r}
set.seed(1997)

sample <- sample(c(TRUE, FALSE), nrow(NB_data), replace=TRUE, prob=c(0.8,0.2))
NB_train  <- NB_data[sample, ]
NB_test   <- NB_data[!sample, ]
```



```{r}
set.seed(120)
Naive_Bayes_Model=naiveBayes(Label ~., data=NB_data)
Naive_Bayes_Model
```

```{r}
NB_Predictions=predict(Naive_Bayes_Model,NB_test)
cm = table(NB_Predictions,NB_test$Label)
```

```{r}
cm
```

```{r}
library(caret)
cms = confusionMatrix(cm)
cms

```

```{r}
train_cm_df = data.frame(cm)

ggplot(data = train_cm_df, mapping = aes(x = NB_Predictions, y = Var2)) +
  geom_tile(aes(fill = Freq), colour = "white") +
  geom_text(aes(label = sprintf("%1.0f", Freq)), vjust = 1) +
  scale_fill_gradient(low = "lightblue", high = "yellow") +
  theme_bw() + theme(legend.position = "none")
```