---
title: "Untitled"
author: "Sangeetha"
date: "2022-10-13"
output: html_document
---

```{r}
library(naivebayes)
library(dplyr)
library(ggplot2)
library(psych)
library(e1071)
```



```{r}
df <- read.csv("../../data/ny-air.csv")
head(df)
```



```{r fig.width= 8, fig.height = 10}
NB_df = select(df, -indicator_data_id, -indicator_id, -geo_type_name, -geo_entity_id, -geo_entity_name, -year_description)
head(NB_df)

```

```{r}
p = ggplot(data = NB_df, aes(x=factor(name)))+
  geom_bar(color = "grey", fill = "lightblue")+
  labs(title = "Air Pollution Category Distribution")+
  xlab ("Category")+
  ylab ("Frequency") +
  theme(panel.background = element_rect(fill = "white"))
# Horizontal bar plot
p + coord_flip()
```

```{r}
set.seed(1997)

sample <- sample(c(TRUE, FALSE), nrow(NB_df), replace=TRUE, prob=c(0.8,0.2))
NB_train1  <- NB_df[sample, ]
NB_test1   <- NB_df[!sample, ]
```

```{r}
set.seed(120)
Naive_Bayes_Model1=naiveBayes(measure ~., data=NB_df)
Naive_Bayes_Model1
```

```{r}
NB_Predictions1=predict(Naive_Bayes_Model1,NB_test1)
cm1 = table(NB_Predictions1,NB_test1$measure)
```


```{r}
cm1
```

```{r}
library(caret)
cms1 = confusionMatrix(cm1)
cms1
```

```{r}
train_cm_df = data.frame(cm1)
```

```{r}
train_cm_df
```


#library("reshape")
#data_melt = melt(NB_df)
#head(data_melt)



#ggp <- ggplot(data_melt, aes(name, measure)) +                           # Create heatmap with ggplot2
#  geom_tile(aes(fill = value))
#ggp  


```{r fig.width=8, fig.height=5}
ggplot(data = train_cm_df, mapping = aes(x = NB_Predictions1, y = Var2)) +
  geom_tile(aes(fill = Freq), colour = "white") +
  geom_text(aes(label = sprintf("%1.0f", Freq)), vjust = 1) +
  scale_fill_gradient(low = "lightblue", high = "yellow") +
  theme_bw() + theme(legend.position = "none")
```